bridge-layout
deltafi-trade/deltafi-app-v2 pull request #173
Opened 2022-07-04 08:24 UTC by RubicLiu

2022-11-11 22:01 UTC, deltafilzr commented
Have done the merge and added this code

2022-11-18 21:53 UTC, pjxthy requested changes
1. Fix lint issues
2. Make sure it does not break the swap, pools, dashboard etc. logic
3. Merge

2022-11-18 22:08 UTC, deltafilzr commented on src/components/BurgerMenu/WalletPanel_v2.tsx
> +                    ></Box>
![image](https://user-images.githubusercontent.com/114944609/202811195-273b680d-83f9-4a7d-8642-6680a78e6dcf.png)

2022-11-18 22:55 UTC, pjxthy requested changes

2022-11-18 22:55 UTC, pjxthy commented on src/components/BurgerMenu/BridgeConnectPanel.tsx
> +      {!!wallet1Connected === !!wallet2Connected ? (
please have better names than wallet1 & wallet2

2022-11-18 22:59 UTC, deltafilzr commented on src/components/BurgerMenu/BridgeConnectPanel.tsx
> +      {!!wallet1Connected === !!wallet2Connected ? (
So change to WalletOne something like this? is this one acceptable?

2022-11-18 23:09 UTC, pjxthy requested changes

2022-11-18 23:09 UTC, pjxthy commented on src/components/Header.tsx
> +      setMenu(true, "connectV2");
why do we have connectV2 here?

2022-11-18 23:16 UTC, pjxthy commented on src/components/Header.tsx
> +      setMenu(true, "connectV2");
// TODO (deltafilzr): rename connectV2 to a better one
setMenu(true, "connectV2");

2022-11-18 23:17 UTC, pjxthy commented on src/components/Header.tsx
> +      setMenu(true, "connectV2");
add a child ticket to Delta-28

2022-11-18 23:53 UTC, pjxthy approved these changes

2022-11-18 23:53 UTC, merged