Token bridge config v1
deltafi-trade/deltafi-app-v2 pull request #188
Opened 2022-11-18 19:30 UTC by deltafilzr

ready for review
added
1. logos
2. configuration file for Polygon and BSC

2022-11-18 19:34 UTC, pjxthy requested changes

2022-11-18 19:34 UTC, pjxthy commented on src/config/bridge/fullDeployConfig.json
> +  "polygon": {
remove all token logos with wh eg public/cryptologos/BNB_wh.png. we do not usually make the difference in logo for wrapped tokens.

also cryptologos -> logos.

2022-11-18 19:34 UTC, pjxthy commented on src/config/bridge/fullDeployConfig.json
> +            "name": "Wrapped Matic",
please be specific on what wrapped tokens. there are a lot of wrapped tokens like wormhole wrapped etc.

2022-11-18 19:38 UTC, deltafilzr commented on src/config/bridge/fullDeployConfig.json
> +  "polygon": {
done!

2022-11-19 00:32 UTC, pjxthy requested changes

2022-11-19 00:32 UTC, pjxthy commented on .prettierignore
> -*.json
why remove json here?

2022-11-19 00:32 UTC, pjxthy commented on src/config/bridge/fullDeployConfig.json
> +      "wormholeChainId": "CHAIN_ID_POLYGON",
i do not think this config is correct.

1. each chain's config should be separate
2. matic token is redundant
3. please remove ploygon and bsc in the toke names. chain param should be a separate one.

2022-11-19 01:29 UTC, pjxthy approved these changes

2022-11-19 01:49 UTC, merged